# Generated by Django 2.1 on 2018-08-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='kind',
            field=models.IntegerField(choices=[(1, 'sim'), (2, 'não')], verbose_name='tipo'),
        ),
    ]
